const FETCH_TRANSPORT_LINE_SEARCH = 'voud/search-points-of-interest/FETCH_TRANSPORT_LINE_SEARCH';
const FETCH_TRANSPORT_LINE_SEARCH_SUCCESS = 'voud/search-points-of-interest/FETCH_TRANSPORT_LINE_SEARCH_SUCCESS';
const FETCH_TRANSPORT_LINE_SEARCH_FAILURE = 'voud/search-points-of-interest/FETCH_TRANSPORT_LINE_SEARCH_FAILURE';
const FETCH_TRANSPORT_LINE_SEARCH_CLEAR = 'voud/search-points-of-interest/FETCH_TRANSPORT_LINE_SEARCH_CLEAR';

const FETCH_RECHARGE_POINTS_SEARCH = 'voud/search-points-of-interest/FETCH_RECHARGE_POINTS_SEARCH';
const FETCH_RECHARGE_POINTS_SEARCH_SUCCESS = 'voud/search-points-of-interest/FETCH_RECHARGE_POINTS_SEARCH_SUCCESS';
const FETCH_RECHARGE_POINTS_SEARCH_FAILURE = 'voud/search-points-of-interest/FETCH_RECHARGE_POINTS_SEARCH_FAILURE';
const FETCH_RECHARGE_POINTS_SEARCH_CLEAR = 'voud/search-points-of-interest/FETCH_RECHARGE_POINTS_SEARCH_CLEAR';

const FETCH_NEXT_POINT = 'voud/search-points-of-interest/FETCH_NEXT_POINT';
const FETCH_NEXT_POINT_SUCCESS = 'voud/search-points-of-interest/FETCH_NEXT_POINT_SUCCESS';
const FETCH_NEXT_POINT_FAILURE = 'voud/search-points-of-interest/FETCH_NEXT_POINT_FAILURE';
const FETCH_NEXT_POINT_CLEAR = 'voud/search-points-of-interest/FETCH_NEXT_POINT_CLEAR';

const FETCH_ARRIVAL_FORECAST = 'voud/search-points-of-interest/FETCH_ARRIVAL_FORECAST';
const FETCH_ARRIVAL_FORECAST_SUCCESS = 'voud/search-points-of-interest/FETCH_ARRIVAL_FORECAST_SUCCESS';
const FETCH_ARRIVAL_FORECAST_FAILURE = 'voud/search-points-of-interest/FETCH_ARRIVAL_FORECAST_FAILURE';
const FETCH_ARRIVAL_FORECAST_CLEAR = 'voud/search-points-of-interest/FETCH_ARRIVAL_FORECAST_CLEAR';

const FETCH_BUS_LINE_SEARCH = 'voud/search-points-of-interest/FETCH_BUS_LINE_SEARCH';
const FETCH_BUS_LINE_SEARCH_SUCCESS = 'voud/search-points-of-interest/FETCH_BUS_LINE_SEARCH_SUCCESS';
const FETCH_BUS_LINE_SEARCH_FAILURE = 'voud/search-points-of-interest/FETCH_BUS_LINE_SEARCH_FAILURE';
const FETCH_BUS_LINE_SEARCH_CLEAR = 'voud/search-points-of-interest/FETCH_BUS_LINE_SEARCH_CLEAR';

const FETCH_ROUTES = 'voud/search-points-of-interest/FETCH_ROUTES';
const FETCH_ROUTES_SUCCESS = 'voud/search-points-of-interest/FETCH_ROUTES_SUCCESS';
const FETCH_ROUTES_FAILURE = 'voud/search-points-of-interest/FETCH_ROUTES_FAILURE';
const FETCH_ROUTES_CLEAR = 'voud/search-points-of-interest/FETCH_ROUTES_CLEAR';

const REQUEST_LIST = 'voud/service-points/REQUEST_LIST';
const REQUEST_LIST_SUCCESS = 'voud/service-points/REQUEST_LIST_SUCCESS';
const REQUEST_LIST_FAILURE = 'voud/service-points/REQUEST_LIST_FAILURE';

export default {
	REQUEST_LIST,
	REQUEST_LIST_SUCCESS,
	REQUEST_LIST_FAILURE,
	FETCH_TRANSPORT_LINE_SEARCH,
	FETCH_TRANSPORT_LINE_SEARCH_SUCCESS,
	FETCH_TRANSPORT_LINE_SEARCH_FAILURE,
	FETCH_TRANSPORT_LINE_SEARCH_CLEAR,
	FETCH_RECHARGE_POINTS_SEARCH,
	FETCH_RECHARGE_POINTS_SEARCH_SUCCESS,
	FETCH_RECHARGE_POINTS_SEARCH_FAILURE,
	FETCH_RECHARGE_POINTS_SEARCH_CLEAR,
	FETCH_NEXT_POINT,
	FETCH_NEXT_POINT_SUCCESS,
	FETCH_NEXT_POINT_FAILURE,
	FETCH_NEXT_POINT_CLEAR,
	FETCH_ARRIVAL_FORECAST,
	FETCH_ARRIVAL_FORECAST_SUCCESS,
	FETCH_ARRIVAL_FORECAST_FAILURE,
	FETCH_ARRIVAL_FORECAST_CLEAR,
	FETCH_BUS_LINE_SEARCH,
	FETCH_BUS_LINE_SEARCH_SUCCESS,
	FETCH_BUS_LINE_SEARCH_FAILURE,
	FETCH_BUS_LINE_SEARCH_CLEAR,
	FETCH_ROUTES,
	FETCH_ROUTES_SUCCESS,
	FETCH_ROUTES_FAILURE,
	FETCH_ROUTES_CLEAR
};
