const CHECK_LAST_TERMS_ACCEPTED = 'voud/usage-terms/CHECK_LAST_TERMS_ACCEPTED';
const CHECK_LAST_TERMS_ACCEPTED_SUCCESS = 'voud/usage-terms/CHECK_LAST_TERMS_ACCEPTED_SUCCESS';
const CHECK_LAST_TERMS_ACCEPTED_FAILURE = 'voud/usage-terms/CHECK_LAST_TERMS_ACCEPTED_FAILURE';

const ACCEPT_CURRENT_TERMS = 'voud/usage-terms/ACCEPT_CURRENT_TERMS';
const ACCEPT_CURRENT_TERMS_SUCCESS = 'voud/usage-terms/ACCEPT_CURRENT_TERMS_SUCCESS';
const ACCEPT_CURRENT_TERMS_FAILURE = 'voud/usage-terms/ACCEPT_CURRENT_TERMS_FAILURE';

export default {
  CHECK_LAST_TERMS_ACCEPTED, CHECK_LAST_TERMS_ACCEPTED_SUCCESS, CHECK_LAST_TERMS_ACCEPTED_FAILURE,
  ACCEPT_CURRENT_TERMS, ACCEPT_CURRENT_TERMS_SUCCESS, ACCEPT_CURRENT_TERMS_FAILURE,
};
