const FETCH_POINTS_OF_INTEREST = 'voud/home/FETCH_POINTS_OF_INTEREST';
const FETCH_POINTS_OF_INTEREST_SUCCESS = 'voud/home/FETCH_POINTS_OF_INTEREST_SUCCESS';
const FETCH_POINTS_OF_INTEREST_FAILURE = 'voud/home/FETCH_POINTS_OF_INTEREST_FAILURE';
const FETCH_POINTS_OF_INTEREST_CLEAR = 'voud/home/FETCH_POINTS_OF_INTEREST_CLEAR';

const FETCH_POINTS_OF_TEMBICI = 'voud/home/FETCH_POINTS_OF_TEMBICI';
const FETCH_POINTS_OF_TEMBICI_SUCCESS = 'voud/home/FETCH_POINTS_OF_TEMBICI_SUCCESS';
const FETCH_POINTS_OF_TEMBICI_FAILURE = 'voud/home/FETCH_POINTS_OF_TEMBICI_FAILURE';
const FETCH_POINTS_OF_TEMBICI_CLEAR = 'voud/home/FETCH_POINTS_OF_TEMBICI_CLEAR';

const FETCH_POINTS_OF_ZAZCAR = 'voud/home/FETCH_POINTS_OF_ZAZCAR';
const FETCH_POINTS_OF_ZAZCAR_SUCCESS = 'voud/home/FETCH_POINTS_OF_ZAZCAR_SUCCESS';
const FETCH_POINTS_OF_ZAZCAR_FAILURE = 'voud/home/FETCH_POINTS_OF_ZAZCAR_FAILURE';
const FETCH_POINTS_OF_ZAZCAR_CLEAR = 'voud/home/FETCH_POINTS_OF_ZAZCAR_CLEAR';

const FETCH_DYNAMIC_POINTS = 'voud/home/FETCH_DYNAMIC_POINTS';
const FETCH_DYNAMIC_POINTS_SUCCESS = 'voud/home/FETCH_DYNAMIC_POINTS_SUCCESS';
const FETCH_DYNAMIC_POINTS_FAILURE = 'voud/home/FETCH_DYNAMIC_POINTS_FAILURE';
const FETCH_DYNAMIC_POINTS_CLEAR = 'voud/home/FETCH_DYNAMIC_POINTS_CLEAR';

const UPDATE_CURRENT_MAP_POSITION = ' voud/home/UPDATE_CURRENT_MAP_POSITION';
const SHOW_DIRECTION_ZAZCAR = ' voud/home/SHOW_DIRECTION_ZAZCAR';

export default {
  FETCH_POINTS_OF_INTEREST, FETCH_POINTS_OF_INTEREST_FAILURE, FETCH_POINTS_OF_INTEREST_SUCCESS, FETCH_POINTS_OF_INTEREST_CLEAR,
  FETCH_POINTS_OF_TEMBICI, FETCH_POINTS_OF_TEMBICI_FAILURE, FETCH_POINTS_OF_TEMBICI_SUCCESS, FETCH_POINTS_OF_TEMBICI_CLEAR,
  FETCH_POINTS_OF_ZAZCAR, FETCH_POINTS_OF_ZAZCAR_SUCCESS, FETCH_POINTS_OF_ZAZCAR_FAILURE, FETCH_POINTS_OF_ZAZCAR_CLEAR,
  UPDATE_CURRENT_MAP_POSITION,
  SHOW_DIRECTION_ZAZCAR,
  FETCH_DYNAMIC_POINTS, FETCH_DYNAMIC_POINTS_FAILURE, FETCH_DYNAMIC_POINTS_SUCCESS, FETCH_DYNAMIC_POINTS_CLEAR
};
