const FETCH_PLACE_SEARCH = 'voud/mobility-services/FETCH_PLACE_SEARCH';
const FETCH_PLACE_SEARCH_SUCCESS = 'voud/mobility-services/FETCH_PLACE_SEARCH_SUCCESS';
const FETCH_PLACE_SEARCH_FAILURE = 'voud/mobility-services/FETCH_PLACE_SEARCH_FAILURE';
const PLACE_SEARCH_CLEAR = 'voud/mobility-services/PLACE_SEARCH_CLEAR';

const FETCH_PREDICTIONS = 'voud/mobility-services/FETCH_PREDICTIONS';
const FETCH_PREDICTIONS_SUCCESS = 'voud/mobility-services/FETCH_PREDICTIONS_SUCCESS';
const FETCH_PREDICTIONS_FAILURE = 'voud/mobility-services/FETCH_PREDICTIONS_FAILURE';
const PREDICTIONS_CLEAR = 'voud/mobility-services/PREDICTIONS_CLEAR';
const SET_PREDICTIONS_SESSION_TOKEN = 'voud/mobility-services/SET_PREDICTIONS_SESSION_TOKEN';

const FETCH_PLACE_DETAILS = 'voud/mobility-services/FETCH_PLACE_DETAILS';
const FETCH_PLACE_DETAILS_SUCCESS = 'voud/mobility-services/FETCH_PLACE_DETAILS_SUCCESS';
const FETCH_PLACE_DETAILS_FAILURE = 'voud/mobility-services/FETCH_PLACE_DETAILS_FAILURE';
const PLACE_DETAILS_CLEAR = 'voud/mobility-services/PLACE_DETAILS_CLEAR';

const SEARCH_CHANGE_DIRECTIONS = 'voud/mobility-services/SEARCH_CHANGE_DIRECTIONS';

const FETCH_ESTIMATES = 'voud/mobility-services/FETCH_ESTIMATES';
const FETCH_ESTIMATES_SUCCESS = 'voud/mobility-services/FETCH_ESTIMATES_SUCCESS';
const FETCH_ESTIMATES_FAILURE = 'voud/mobility-services/FETCH_ESTIMATES_FAILURE';
const ESTIMATES_CLEAR = 'voud/mobility-services/ESTIMATES_CLEAR';

const SELECT_SERVICE = 'voud/mobility-services/SELECT_SERVICE';

const FETCH_ESTIMATE_ACTION = 'voud/mobility-services/FETCH_ESTIMATE_ACTION';
const FETCH_ESTIMATE_ACTION_SUCCESS = 'voud/mobility-services/FETCH_ESTIMATE_ACTION_SUCCESS';
const FETCH_ESTIMATE_ACTION_FAILURE = 'voud/mobility-services/FETCH_ESTIMATE_ACTION_FAILURE';

export default {
  FETCH_PLACE_SEARCH, FETCH_PLACE_SEARCH_SUCCESS, FETCH_PLACE_SEARCH_FAILURE, PLACE_SEARCH_CLEAR,
  FETCH_PREDICTIONS, FETCH_PREDICTIONS_SUCCESS, FETCH_PREDICTIONS_FAILURE, PREDICTIONS_CLEAR, SET_PREDICTIONS_SESSION_TOKEN,
  FETCH_PLACE_DETAILS, FETCH_PLACE_DETAILS_SUCCESS, FETCH_PLACE_DETAILS_FAILURE, PLACE_DETAILS_CLEAR,
  SEARCH_CHANGE_DIRECTIONS,
  FETCH_ESTIMATES, FETCH_ESTIMATES_SUCCESS, FETCH_ESTIMATES_FAILURE, ESTIMATES_CLEAR,
  SELECT_SERVICE, FETCH_ESTIMATE_ACTION, FETCH_ESTIMATE_ACTION_SUCCESS, FETCH_ESTIMATE_ACTION_FAILURE,
};
